import exceptions.SimulatorException;
import graph.Vertex;
import input.Reader;
import org.apache.commons.cli.*;
import simulator.Simulator;
import taxi.Customer;
import taxi.Taxi;

import java.io.File;
import java.util.ArrayList;

/**
 * Main entry point for the interpreter
 */
public class Interpreter {

    private Reader inputReader;
    private Reader outputReader;

    private ArrayList<String> input;
    private ArrayList<String> output;

    public Interpreter() {

        inputReader = new Reader(input);
        outputReader = new Reader(output);

    }

    /**
     * Initialises readers for the algorithm
     */
    private void setup() {

        // Clear buffers
        input = new ArrayList<>();
        output = new ArrayList<>();

        // Register readers to get input and output from the algorithm
        TaxiScanner.getInstance().registerInputReader(inputReader);
        TaxiScanner.getInstance().registerOutputReader(outputReader);

    }

    /**
     * Runs the algorithm with a give test case file
     *
     * @param testCase Test case
     */
    public void run(File testCase) {

        // Run setup
        setup();

        // Set test case
        TaxiScanner.setInputFile(testCase);

        // Keep track of time and run the algorithm
        long startTime = System.currentTimeMillis();
        (new Main()).run();
        long endTime = System.currentTimeMillis();
        long runTime = startTime - endTime;

        Simulator simulator = new Simulator(input, output);

        boolean success = simulator.simulate();

        System.out.println("Time: " + (endTime - startTime) + " ms");

    }

    public void run(/* TODO Run simulation with data generated by the test factory */) {

    }

    public static void main(String[] args) {
        Options options = new Options(); // Use apache commons cli api to create options.
        CommandLineParser parser = new DefaultParser();
        CommandLine cmd;

        boolean justAlgorithm = false;
        boolean printHelp = false;
        File inputFile = null;

        options.addOption("h", "help", false, "Prints this help message.");
        options.addOption("a", "just-algorithm", false,
                "Just run the algorithm, without running the interpreter.");
        options.addOption("i", "input", true, "Input file.");

        try {
            cmd = parser.parse(options, args);
            printHelp = cmd.hasOption("h");
            justAlgorithm = cmd.hasOption("a");
            inputFile = cmd.hasOption("i") ? new File(cmd.getOptionValue("i")) : null;
        } catch (ParseException e) {
            System.out.println("Error while parsing arguments, continuing normal execution.");
            e.printStackTrace();
        }
        
        if (printHelp) {
            HelpFormatter formatter = new HelpFormatter();
            formatter.printHelp( "interpreter", options );
            return;
        }

        if (inputFile != null) {
            System.out.println("Using specified input file.");
            TaxiScanner.setInputFile(inputFile);
        }

        if (justAlgorithm) {
            System.out.println("Running just the algorithm...");
            (new Main()).run();
            return;
        }

        System.out.println("Executing interpreter");
        (new Interpreter()).run();
    }
}
