package CLI;

/**
 *
 */
public enum ExecutionMode {
    /* Indicates that the algorithm should be run with a specified input file */
    SPECIFIED_INPUT_FILE,
    /* Indicates that the algorithm should be run with a test case generated by the test factory */
    GENERATED_TEST_CASE,
    /* Indicates that the algorithm should be run with generated test cases by the test factory */
    BULK_TESTING,
    /* Prints the help message */
    HELP_MESSAGE
}
